DB = {
    'projects': [
        {
            'id': 0,
            'name': 'Shiru Cafe',
            'start_date': 1576834736,
            'end_date': -1,
            'expected_end': 1576837736,
            'progress': [0],
            'location': [2800, 7700, 400],
            'schema': [
                {
                    'q': 'is this much',
                    'a': ['yes', 'no'],
                },
                {
                    'q': 'is this honest work',
                    'a': ['yes', 'no'],
                },
            ],
        },
        {
            'id': 1,
            'name': 'New LHC',
            'start_date': 1576834776,
            'end_date': 1576838776,
            'expected_end': 1576837736,
            'progress': [0, 10, 30, 50, 90, 92, 100],
            'location': [2850, 7700, 4000],
            'schema': [
                {
                    'q': 'is this much',
                    'a': ['yes', 'no'],
                },
                {
                    'q': 'is this honest work',
                    'a': ['yes', 'no'],
                },
            ],
        },
    ],
    'users': [
        {
            'id': 0,
            'username': 'anish',
            'password': 'anish',
            'is_admin': True,
            'is_verified': True,
        },
        {
            'id': 1,
            'username': 'vaibhav',
            'password': 'vaibhav',
            'is_admin': False,
            'is_verified': True,
        },
        {
            'id': 2,
            'username': 'manas',
            'password': 'manas',
            'is_admin': False,
            'is_verified': True,
        },
        {
            'id': 3,
            'username': 'shubham',
            'password': 'shubham',
            'is_admin': False,
            'is_verified': True,
        },
        {
            'id': 4,
            'username': 'supratik',
            'password': 'supratik',
            'is_admin': False,
            'is_verified': False,
        }
    ],
    'surveys': [
        {
            'id': 0,
            'user': 1,
            'project': 0,
            'timestamp': 1284101485,
            'image': '1576842155__btn-live-preview.png',
            'location': [1, 2, 4],
            'ques': {
                'is this much': 'no',
                'is this honest work': 'yes',
            },
        },
        {
            'id': 1,
            'user': 2,
            'project': 0,
            'timestamp': 1284101486,
            'image': '1576842155__btn-live-preview.png',
            'location': [1, 2, 4],
            'ques': {
                'is this much': 'no',
                'is this honest work': 'no',
            },
        },
        {
            'id': 2,
            'user': 3,
            'project': 0,
            'timestamp': 1284101487,
            'image': '1576842155__btn-live-preview.png',
            'location': [1, 2, 4],
            'ques': {
                'is this much': 'yes',
                'is this honest work': 'yes',
            },
        },
        {
            'id': 3,
            'user': 1,
            'project': 0,
            'timestamp': 1284101488 + 86400,
            'image': '1576842155__btn-live-preview.png',
            'location': [1, 2, 4],
            'ques': {
                'is this much': 'no',
                'is this honest work': 'yes',
            },
        },
        {
            'id': 4,
            'user': 3,
            'project': 0,
            'timestamp': 1284101489 + 86400,
            'image': '1576842155__btn-live-preview.png',
            'location': [1, 2, 4],
            'ques': {
                'is this much': 'yes',
                'is this honest work': 'no',
            },
        },
    ],
    'issues': [
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 0,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 1,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [2850, 7700, 4000],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
        {
            'id': 2,
            'timestamp': 1284101487,
            'image': '5.jpg',
            'location': [1, 2, 4],
            'title': 'Walking on the moon in Bangalore',
            'description': 'This time on roller coaster',
            'level': 0,
            'level_dates': [1284101487],
            'user': 0
        },
    ],
}
